
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CC.Models.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Customer
{

    public int id { get; set; }

    public string first_name { get; set; }

    public string last_name { get; set; }

    public string address { get; set; }

    public string phone_number { get; set; }

    public string user_id { get; set; }

    public Nullable<System.DateTime> birthday { get; set; }

    public string notes { get; set; }

    public string phone { get; set; }

}

}
