
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CC.Models.Database
{

using System;
    using System.Collections.Generic;
    
public partial class LoanMoney
{

    public int id { get; set; }

    public string person_name { get; set; }

    public Nullable<System.DateTime> loan_date { get; set; }

    public string user_id { get; set; }

    public Nullable<decimal> loan_sum { get; set; }

    public Nullable<System.DateTime> return_date { get; set; }

    public Nullable<bool> loan_status { get; set; }

    public string description { get; set; }

    public int currency_id { get; set; }

}

}
