
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CC.Models.Database
{

using System;
    using System.Collections.Generic;
    
public partial class MaterialToBuy
{

    public Nullable<long> id { get; set; }

    public Nullable<int> unit_id { get; set; }

    public int user_id { get; set; }

    public string produce_name { get; set; }

    public double quantity { get; set; }

    public Nullable<bool> is_buy { get; set; }

}

}
