

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CC.Models.Database
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ExcelentConstructObjectMaterial : DbContext
{
    public ExcelentConstructObjectMaterial()
        : base("name=ExcelentConstructObjectMaterial")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<ObjectMaterial> ObjectMaterials { get; set; }

}

}

