
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CC.Models.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Treatment
{

    public int customer_id { get; set; }

    public System.DateTime current_date { get; set; }

    public Nullable<System.DateTime> next_date { get; set; }

    public string current_work { get; set; }

    public string next_work { get; set; }

    public Nullable<int> treatment_type { get; set; }

    public int id { get; set; }

}

}
