//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermission
    {
        public int id { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<bool> can_view { get; set; }
        public Nullable<bool> can_add { get; set; }
        public Nullable<bool> can_edit { get; set; }
        public Nullable<bool> can_delete { get; set; }
        public System.Guid user_id { get; set; }
        public int module_id { get; set; }
    }
}
