//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkersGroupDetail
    {
        public int workers_groups_id { get; set; }
        public int worker_id { get; set; }
        public Nullable<int> work_part { get; set; }
    }
}
