//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        public int ID { get; set; }
        public string Location { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<int> Parent_Id { get; set; }
        public string Description { get; set; }
        public int User_Id { get; set; }
        public string UserId { get; set; }
    }
}
