//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerSpeciality
    {
        public int worker_id { get; set; }
        public int speciality_id { get; set; }
        public string worker_level { get; set; }
    }
}
